import ast
import os
import re
from typing import List, Optional, Union

import numpy as np
from torch.nn.functional import softmax

from czi.ai.rbio.model.verifiers import (
    verify_gene_info_discrete,
    verify_gene_info_llh,
    verify_gene_info_rouge_scores,
)
from czi.ai.rbio.utils.utils import (
    extract_binary_answer,
    extract_gene_info,
    extract_think,
)


def reward_answer_against_go_ontology(
    completion: str,
    kw_genes: List[str],
    go_verifier_type: str,
    go_ontology_type: str,
    gene2annotations: dict,
    rouge_scorer=None,
    model=None,
    tokenizer=None,
) -> float:
    """
    Compute soft verification and reward scores against the GO Ontology

    Args:
        completion: answer generated by the model
        kw_genes: keywords, assumed to be genes (gene_perturbed, gene_monitored) i.e. gene_A|gene_B
        go_verifier_type: type of GO verifier - one of ['discrete', 'rouge', 'llh']
        go_ontology_type: type of GO ontology to use - one of ['F', 'C', 'P']
        gene2annotations: mapping from a gene to its GO annotations
        rouge_sccorer: ROUGE scorer
        model: trained reasoning model; used to compute LLH scores
        tokenizer: tokenizer corresponding to the reasoning model; used to tokenize the gene annotations before computing the LLH

    """
    rewards = [0.0]

    # Generate rewards for each of the keywods, which are
    # likely to be gene_perturbed and gene_monitored
    for gene in kw_genes:
        gene_info = extract_gene_info(completion, gene)
        # No gene info
        if gene_info == "No information.":
            continue
        elif go_verifier_type == "discrete":
            go_reward_discrete = verify_gene_info_discrete(
                gene_info, gene, gene2annotations
            )
            rewards.append(go_reward_discrete)
        elif go_verifier_type == "rouge":
            go_reward_rouge1, go_reward_rouge2, go_reward_rougel = (
                verify_gene_info_rouge_scores(
                    gene_info, gene, gene2annotations, rouge_scorer
                )
            )
            rewards.extend([go_reward_rouge1, go_reward_rouge2, go_reward_rougel])
        elif go_verifier_type == "llh":
            go_reward_llh = verify_gene_info_llh(
                gene, gene2annotations, model, tokenizer, go_ontology_type
            )
            rewards.append(go_reward_llh)
    # Take the mean of the aggregated rewards, usually one for
    # each of the two genes considered: gene_perturbed and gene_monitored
    return np.array(rewards).mean()


def reward_answer_against_label(
    completion: str, classes: str, class_confidence: str
) -> float:
    answer = extract_binary_answer(completion)
    if answer is None:
        return 0.0

    answer = "yes" if answer else "no"

    possible_classes = classes.split("|")
    confidences = [float(c) for c in class_confidence.split("|")]

    for label, conf in zip(possible_classes, confidences):
        if answer == label.strip().lower():
            return conf

    return 0.0


def has_at_least_one_think(text):
    return 1 if re.search(r"<think>.*?</think>", text, re.DOTALL) else 0


def has_at_least_one_gene_info(text):
    return 1 if re.search(r"<gene_info>.*?</gene_info>", text, re.DOTALL) else 0


def low_untagged_ratio(text):
    text_no_tags = re.sub(r"</?(think|answer)>", "", text)
    total_words = len(re.findall(r"\b\w+\b", text_no_tags))

    tagged_words = 0
    for tag in re.findall(r"<(think|answer)>(.*?)</\1>", text, re.DOTALL):
        tagged_words += len(re.findall(r"\b\w+\b", tag[1]))
    ratio = tagged_words / total_words if total_words else 0

    return ratio


def starts_with_think(text):
    return 1 if re.match(r"^\s*<think>", text) else 0


def is_not_too_long(text):
    word_count = len(re.findall(r"\b\w+\b", text))
    return 1 if word_count <= 200 else 200 / word_count


def has_one_answer(text):
    matches = re.findall(r"<answer>.*?</answer>", text, re.DOTALL)
    return 1 if len(matches) == 1 else 0


def answer_after_thinks(text):
    think_tags = list(re.finditer(r"</think>", text))
    answer_match = re.search(r"<answer>", text)
    if not answer_match:
        return 0
    if not think_tags:
        return 0
    last_think_end = think_tags[-1].end()
    return 1 if answer_match.start() > last_think_end else 0


def thinks_have_text(text):
    return (
        1
        if all(
            re.search(r"\S", match)
            for match in re.findall(r"<think>(.*?)</think>", text, re.DOTALL)
        )
        else 0
    )


def keywords_mentioned_in_think(text: str, keywords: str) -> float:
    """
    Checks how many keywords from the pipe-separated string are mentioned in the think sections.
    Returns a score between 0 and 1 representing the ratio of found keywords.
    """
    # Split keywords and filter out empty strings
    keyword_list = [k for k in keywords.split("|") if k]

    # If no keywords to check, return 1.0
    if not keyword_list:
        return 1.0

    think_contents = extract_think(text)

    # If no think sections, return 0.0
    if not think_contents:
        return 0.0

    # Count how many keywords are found in any think section
    found_keywords = 0

    for keyword in keyword_list:
        if keyword in think_contents:
            found_keywords += 1

    # Return the ratio of found keywords to total keywords
    return found_keywords / len(keyword_list)


def no_nested_tags(text):
    # Match all <think>...</think> and <answer>...</answer> blocks
    blocks = re.finditer(r"<(think|answer)>(.*?)</\1>", text, re.DOTALL)

    for block in blocks:
        tag_type = block.group(1)
        inner_text = block.group(2)
        # Look for any nested <think> or <answer> inside the block
        if re.search(r"</?(think|answer)>", inner_text, re.DOTALL):
            return 0
    return 1


def all_tags_properly_closed(text):
    tag_stack = []
    tag_pattern = re.finditer(r"</?(think|answer)>", text)

    for tag in tag_pattern:
        tag_text = tag.group()
        tag_type = re.match(r"</?(think|answer)>", tag_text).group(1)

        if tag_text.startswith("</"):
            # closing tag
            if not tag_stack or tag_stack[-1] != tag_type:
                return 0  # orphan or mismatched closing tag
            tag_stack.pop()
        else:
            # opening tag
            tag_stack.append(tag_type)

    return 1 if not tag_stack else 0  # stack must be empty if all matched


def has_limited_thinks(text):
    matches = re.findall(r"<think>.*?</think>", text, re.DOTALL)
    return 1 if len(matches) <= 1 else 1 / (len(matches) * 4)


def ends_with_answer(text):
    return 1 if text.endswith("</answer>") else 0


def has_any_tag(text):
    return 1 if re.search(r"</?(think|answer)>", text) else 0


def gene_info_has_enough_text(text):
    gene_info = extract_gene_info(text, "")
    word_count = len(re.findall(r"\b\w+\b", gene_info))
    return 1 if word_count >= 10 else word_count / 10


def think_after_gene_info(text):
    """
    For the GO Ontology soft verification case, check that the thinking
    happens after the gene info is retrieved, to enforce that the model uses the
    gene information during its thinking process.
    """
    gene_info_tags = list(re.finditer(r"</gene_info>", text))
    think_match = re.search(r"<think>", text)
    if not think_match:
        return 0
    if not gene_info_tags:
        return 0
    last_gene_info_end = gene_info_tags[-1].end()
    return 1 if think_match.start() > last_gene_info_end else 0


def answer_after_gene_info(text):
    """
    For the GO Ontology soft verification case, check that the answer is generated
    after the gene info is retrieved, to enforce that the model uses the
    gene information in generating its answer.
    """
    think_tags = list(re.finditer(r"</gene_info>", text))
    answer_match = re.search(r"<answer>", text)
    if not answer_match:
        return 0
    if not think_tags:
        return 0
    last_think_end = think_tags[-1].end()
    return 1 if answer_match.start() > last_think_end else 0


def starts_with_gene_info(text):
    """
    Check that text completion starts with <gene_info>
    """
    return 1 if re.match(r"^\s*<gene_info>", text) else 0


def gene_infos_have_text(text):
    """
    Check that gene_info tags have text inside them
    """
    return (
        1
        if all(
            re.search(r"\S", match)
            for match in re.findall(r"<gene_info>(.*?)</gene_info>", text, re.DOTALL)
        )
        else 0
    )


def composite_formatting_reward(text, use_go):
    at_least_one_think = has_at_least_one_think(text)
    has_tags = has_any_tag(text)
    checks = [
        at_least_one_think,
        low_untagged_ratio(text),
        # is_not_too_long(text),
        has_one_answer(text),
        answer_after_thinks(text),
        thinks_have_text(text) * at_least_one_think,
        no_nested_tags(text) * has_tags,
        has_limited_thinks(text) * at_least_one_think,
        all_tags_properly_closed(text) * has_tags,
        ends_with_answer(text),
        starts_with_think(text),
    ]
    # if use_go_ontology, remove the dependency to start_with_think,
    # and enforce that it starts with <gene_info></gene_info>,
    # and add additional checks
    if use_go:
        checks = checks[:-1]
        checks.extend(
            [
                gene_info_has_enough_text(text),
                think_after_gene_info(text),
                answer_after_gene_info(text),
                gene_infos_have_text(text),
                starts_with_gene_info(text),
            ]
        )
    return sum(checks) / len(checks)  # normalized score from 0 to 1


def reasoning_advantage_reward(
    model, tokenizer, system_prompt, user_prompt, completion, label
):
    answer = extract_binary_answer(completion)

    if answer is not None:
        if answer:
            answer = ["yes", " yes", "yes ", " yes "]
        else:
            answer = ["no", " no", "no ", " no "]

    else:
        return 0

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    prompt_with_tt = (
        prompt + " <think> " + extract_think(completion) + " </think> <answer>"
    )

    prompt_without_tt = prompt + " <think> </think> <answer>"

    def compute_score(prompt, token_ids):
        inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
        outputs = model.generate(
            **inputs,
            max_new_tokens=1,
            return_dict_in_generate=True,
            output_scores=True,
            output_logits=True,
        )

        scores = []
        for token_id in token_ids:

            probability = softmax(outputs.logits[0][0])[token_id]

            scores.append(probability)

        return max(scores)

    t_ids = tokenizer(answer)["input_ids"]

    token_ids = []
    for t_id in t_ids:
        token_ids.extend(t_id)

    score_without_tt = compute_score(prompt_without_tt, token_ids=token_ids)

    score_with_tt = compute_score(prompt_with_tt, token_ids=token_ids)

    reasoning_advantage = score_with_tt - score_without_tt

    if reasoning_advantage > 0:
        reasoning_advantage = 1.0

    return reasoning_advantage
