name: Lint with Black
run-name: ${{ github.actor }} linting code in ${{ github.repository }}/${{ github.ref }}
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint
        run: |
          pip install -e ${{ github.workspace }}/rbio
          black ${{ github.workspace }}/rbio --check
      - run: echo "Linting has exited with status ${{ job.status }}."