from trl import GRPOConfig, GRPOTrainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import argparse
from transformers import pipeline
import mlflow
import pandas as pd
import os

os.environ["MLFLOW_TRACKING_USERNAME"] = "your_czi_email"
os.environ["MLFLOW_TRACKING_PASSWORD"] = "your_mlflow_password"

import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
handler = logging.StreamHandler()
formatter = logging.Formatter("%(asctime)s-%(levelname)s-%(message)s")
handler.setFormatter(formatter)
logger.addHandler(handler)

TRACKING_URI = "http://mlflow-api.mlflow.svc.cluster.local:5000"
EXP_NAME = "rbio"
mlflow.set_tracking_uri(TRACKING_URI)
mlflow.set_experiment(EXP_NAME)


def get_binary_predictions(llm_predictions, is_binary=False):
    """
    Parses a list of predictions coming from an LLM into binary Yes/No answers

    Args:
        predictions: predictions coming from an llm
    """
    preds = [x[0]["generated_text"][1]["content"] for x in llm_predictions]
    if not is_binary:
        # simple proxy for getting a 'Yes' from an LLM answer; should be developed further
        binary_preds = [x.startswith("Yes") for x in preds]
    else:
        # case for when the llm is asked to only output Yes/No
        binary_preds = [x.strip() == "Yes" for x in preds]
    return binary_preds


def get_metrics(preds, true):
    """
    Compute metrics for a set of predictions and ground truth. Prints metrics and logs to mlflow

    Args:
        preds: predictions
        true: ground truth
    """
    accuracy = accuracy_score(true, preds)
    p, r, f1, support = precision_recall_fscore_support(true, preds, average="macro")

    print(f"Accuracy: {accuracy}, Precision: {p}, Recall: {r}, F1: {f1}")
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", p)
    mlflow.log_metric("recall", r)
    mlflow.log_metric("F1", f1)


def parse_arguments():
    """
    Parses command-line arguments
    """
    parser = argparse.ArgumentParser(description="Biological Reasoning")
    parser.add_argument("--reward-type", default="none", type=str)
    parser.add_argument("--model-type", default="Qwen/Qwen2-0.5B-Instruct", type=str)
    parser.add_argument(
        "--task",
        default="gene_de_expression",
        type=str,
        help="One of: gene_de_expression, gene_dir_change",
    )
    parser.add_argument("--dataset", default="pertqa_K562", type=str)
    parser.add_argument("--sanity-check", default=True, action="store_true")
    parser.add_argument("--num-samples", default=10, type=int)
    parser.add_argument("--strict-binary", default=False)

    args = parser.parse_args()
    return args


def generate_test_preds_df(
    test_predictions,
    test_binary_predictions,
    run_name,
    dir_path="predictions/rbio-Qwen",
):
    """
    Parses test predictions as generated by the LLM and adds them to a pandas dataframe.
    Saves the dataframe under predictions/run_name

    Args:
        test_predictions: test predictions, as generated by the LLM
        test_binary_predictions: test predictions, parsed into
    """
    questions = []
    answers = []
    for x in test_predictions:
        qa = x[0]["generated_text"]
        questions.append(qa[0]["content"])
        answers.append(qa[1]["content"])
    # test_predictions_dict = [{'question' : question_answer, 'answer' : question_answer} for x in test_predictions for question_answer in x[0]['generated_text']]
    test_df = pd.DataFrame({"question": questions, "answer": answers})
    if not os.path.exists(dir_path):
        os.makedirs(dir_path, exist_ok=True)
    test_df.to_csv(f"predictions/{run_name}.csv")


if __name__ == "__main__":
    logger.info("Hi there!")
    args = parse_arguments()
    reward_mode = args.reward_type
    model = args.model_type
    dataset = args.dataset
    num_samples = args.num_samples

    logger.info("Generating dataset ..")

    if dataset == "pertqa_K562":
        train_dataset, test_dataset, X_train_keys, X_test_keys = (
            generate_dataset_from_pertqa("k562", logger, num_samples)
        )
        train_dataset = train_dataset.map(
            lambda x: generate_prompt_column(x, args.strict_binary, args.task)
        )
        test_dataset = test_dataset.map(
            lambda x: generate_prompt_column(x, args.strict_binary, args.task)
        )
        train_gt = [x["label"] == 1 for x in train_dataset]
        test_gt = [x["label"] == 1 for x in test_dataset]
    elif dataset == "norman" and args.task == "cell_cycle_position":
        test_dataset = generate_dataset_from_norman_query(args.task)

    run_name = f"rbio-{args.model_type}-{args.reward_type}-{args.task}-{args.dataset}-num-samples-{args.num_samples}-reasoning-trace-{args.strict_binary==False}"
    mlflow.start_run(run_name=run_name)
    mlflow.log_param("model_type", args.model_type)
    mlflow.log_param("reward_type", args.reward_type)
    mlflow.log_param("task", args.task)
    mlflow.log_param("dataset", args.dataset)
    mlflow.log_param("binary_output", args.strict_binary)

    if reward_mode == "none":
        logger.info(f"I am not using any reward model. Just {model}")
        pipe = pipeline("text-generation", model=model, max_length=1024)
        # messages_list_train = [[{"role" : "user", "content" : x['prompt']}] for x in train_dataset]
        messages_list_test = [
            [{"role": "user", "content": x["prompt"]}] for x in test_dataset
        ]
        logger.info(f"I am now generating predictions...")
        test_predictions = pipe(messages_list_test)
        test_binary_predictions = get_binary_predictions(test_predictions)
        generate_test_preds_df(test_predictions, test_binary_predictions, run_name)
        logger.info(f"Finished generating predictions. Now computing metrics ...")
        get_metrics(test_binary_predictions, test_gt)
        logger.info(f"Finished generating metrics!")
    else:
        if reward_mode == "r_len":
            rewards = [reward_len]

        training_args = GRPOConfig(output_dir="Qwen2-0.5B-GRPO", logging_steps=10)
        trainer = GRPOTrainer(
            model=model,
            reward_funcs=rewards,
            args=training_args,
            train_dataset=train_dataset,
        )
        trainer.train()
        test_predictions = trainer.predict(test_dataset)
        print(test_predictions)
